# generated by datamodel-codegen:
#   filename:  openapi.json

from __future__ import annotations

from enum import Enum

from pydantic import (
    BaseModel,
    ConfigDict,
    Field,
    PositiveFloat,
    RootModel,
    confloat,
    conint,
    constr,
)


class Type(Enum):
    MaxAbs = 'MaxAbs'


class Aggregation1(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    type: Type


class Type1(Enum):
    Max = 'Max'


class Aggregation2(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    type: Type1


class Type2(Enum):
    Min = 'Min'


class Aggregation3(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    type: Type2


class Type3(Enum):
    AtFraction = 'AtFraction'


class Aggregation4(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    fraction: confloat(ge=0.0, le=1.0)
    type: Type3


class Type4(Enum):
    Start = 'Start'


class Aggregation5(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    type: Type4


class Type5(Enum):
    End = 'End'


class Aggregation6(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    type: Type5


class Aggregation(
    RootModel[
        Aggregation1
        | Aggregation2
        | Aggregation3
        | Aggregation4
        | Aggregation5
        | Aggregation6
    ]
):
    root: (
        Aggregation1
        | Aggregation2
        | Aggregation3
        | Aggregation4
        | Aggregation5
        | Aggregation6
    ) = Field(
        ...,
        description='How a member force is reduced to a single value along the member.\nInternally tagged (`{"type": …}`) so every variant is an object — a mixed\nbare-string/object `oneOf` breaks the cloud TS generator.',
    )


class AnalysisOrder(Enum):
    LINEAR = 'LINEAR'
    NONLINEAR = 'NONLINEAR'


class BucklingCurve(Enum):
    A0 = 'A0'
    A = 'A'
    B = 'B'
    C = 'C'
    D = 'D'


class BucklingRestraint(BaseModel):
    node_id: conint(ge=0) = Field(
        ...,
        description="Node (on one of the member set's members) where the restraint acts.",
    )
    restrains_local_y: bool | None = Field(
        None, description="Restrains displacement along the member's local y axis."
    )
    restrains_local_z: bool | None = Field(
        None, description="Restrains displacement along the member's local z axis."
    )
    restrains_torsion: bool | None = Field(
        None,
        description='Restrains twist (rotation about the local x axis), i.e. a\nlateral-torsional restraint.',
    )


class CalcStep(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    formula: str
    label: str
    substituted: str
    unit: str
    value: float


class DensityUnit(Enum):
    kg_m3 = 'kg/m3'
    kg_mm3 = 'kg/mm3'


class Dimensionality(Enum):
    field_2D = '2D'
    field_3D = '3D'


class DirectionalCombination(Enum):
    SRSS = 'SRSS'
    PERCENT30 = 'PERCENT30'


class DispComponent(Enum):
    Dx = 'Dx'
    Dy = 'Dy'
    Dz = 'Dz'
    Rx = 'Rx'
    Ry = 'Ry'
    Rz = 'Rz'
    Magnitude = 'Magnitude'


class Ec3SectionParams(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    a_eff: float | None = Field(
        None,
        description="Effective area for class 4 sections (EN 1993-1-5 §4.3), in the model's\narea unit. Required together with `wel_y_eff` to run EC3 checks on a\nclass 4 section.",
    )
    buckling_curve_lt: BucklingCurve | None = None
    buckling_curve_y: BucklingCurve | None = None
    buckling_curve_z: BucklingCurve | None = None
    section_class: conint(ge=0) | None = Field(
        None,
        description='Cross-section class 1–4 (EN 1993-1-1 §5.5). Class 4 needs effective\nproperties (currently a limitation — see the EC3 evaluator).',
    )
    wel_y_eff: float | None = Field(
        None,
        description="Effective elastic section modulus about y (major axis) for class 4\nsections (EN 1993-1-5), in the model's section-modulus unit.",
    )
    wel_z_eff: float | None = Field(
        None,
        description="Effective elastic section modulus about z (minor axis) for class 4\nsections (EN 1993-1-5), in the model's section-modulus unit.",
    )
    z_j: float | None = Field(
        None,
        description="Mono-symmetry parameter `z_j` (EN 1993-1-1 / NCCI SN030) in the model's\nlength unit; 0 for doubly-symmetric sections. Enables the general LTB\n`M_cr` (used with the spec's C2/C3/z_g).",
    )


class EigenLoadRef1(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    LoadCase: conint(ge=0) = Field(..., description='Reference a load case by id.')


class EigenLoadRef2(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    LoadCombination: conint(ge=0) = Field(
        ..., description='Reference a load combination by id.'
    )


class EigenLoadRef(RootModel[EigenLoadRef1 | EigenLoadRef2]):
    root: EigenLoadRef1 | EigenLoadRef2 = Field(
        ...,
        description='Which load drives the reference stress state for a linear buckling analysis.\nIts first-order member axial forces scale linearly with the load, so the\nreturned eigenvalue is the critical load factor `α_cr` directly.',
    )


class EntityGroup(BaseModel):
    id: conint(ge=0)
    member_ids: list[conint(ge=0)] | None = None
    member_set_ids: list[conint(ge=0)] | None = None
    name: str | None = None
    node_ids: list[conint(ge=0)] | None = None
    plate_element_ids: list[conint(ge=0)] | None = Field(
        None, description='Generated plate finite elements.'
    )
    plate_surface_ids: list[conint(ge=0)] | None = Field(
        None, description='Modeled plate surfaces.'
    )
    support_ids: list[conint(ge=0)] | None = None
    work_axis_ids: list[conint(ge=0)] | None = None
    work_plane_ids: list[conint(ge=0)] | None = None


class Type6(Enum):
    Member = 'Member'


class EntityRef1(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    member_id: conint(ge=0)
    type: Type6


class Type7(Enum):
    MemberSet = 'MemberSet'


class EntityRef2(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    memberset_id: conint(ge=0)
    type: Type7


class Type8(Enum):
    PlateElement = 'PlateElement'


class EntityRef3(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    plate_element_id: conint(ge=0)
    type: Type8


class Type9(Enum):
    PlateSurface = 'PlateSurface'


class EntityRef4(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    plate_surface_id: conint(ge=0)
    type: Type9


class EntityRef(RootModel[EntityRef1 | EntityRef2 | EntityRef3 | EntityRef4]):
    root: EntityRef1 | EntityRef2 | EntityRef3 | EntityRef4 = Field(
        ...,
        description='Which entity a result belongs to. A tagged union (`{"type": …, "<kind>_id": …}`)\nso exactly one target kind is set — consistent with `EntitySelector` and\n`PlatePressureTarget`.',
    )


class Type10(Enum):
    AllMembers = 'AllMembers'


class EntitySelector1(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    type: Type10


class Id(RootModel[conint(ge=0)]):
    root: conint(ge=0)


class Type11(Enum):
    Members = 'Members'


class EntitySelector2(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    ids: list[Id] = Field(..., min_length=1)
    type: Type11


class Type12(Enum):
    MemberSets = 'MemberSets'


class EntitySelector3(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    ids: list[Id] = Field(..., min_length=1)
    type: Type12


class Type13(Enum):
    MemberClassification = 'MemberClassification'


class EntitySelector4(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    type: Type13
    value: str


class Type14(Enum):
    AllPlates = 'AllPlates'


class EntitySelector5(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    type: Type14


class Type15(Enum):
    PlateSurfaces = 'PlateSurfaces'


class EntitySelector6(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    ids: list[Id] = Field(..., min_length=1)
    type: Type15


class Type16(Enum):
    PlateElements = 'PlateElements'


class EntitySelector7(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    ids: list[Id] = Field(..., min_length=1)
    type: Type16


class EntitySelector(
    RootModel[
        EntitySelector1
        | EntitySelector2
        | EntitySelector3
        | EntitySelector4
        | EntitySelector5
        | EntitySelector6
        | EntitySelector7
    ]
):
    root: (
        EntitySelector1
        | EntitySelector2
        | EntitySelector3
        | EntitySelector4
        | EntitySelector5
        | EntitySelector6
        | EntitySelector7
    ) = Field(
        ...,
        description='Which entities a check applies to. Internally tagged (`{"type": …}`) so every\nvariant is an object (a mixed bare-string/object `oneOf` breaks the cloud TS\ngenerator).',
    )


class ForceUnit(Enum):
    N = 'N'
    kN = 'kN'


class GeneralInfo(BaseModel):
    author: str
    project_name: str
    version: str


class GeometryProperty(Enum):
    Length = 'Length'


class GroundType(Enum):
    A = 'A'
    B = 'B'
    C = 'C'
    D = 'D'
    E = 'E'


class InteractionMethod(Enum):
    AnnexA = 'AnnexA'
    AnnexB = 'AnnexB'


class LengthUnit(Enum):
    mm = 'mm'
    cm = 'cm'
    m = 'm'


class LimitState(Enum):
    SLS = 'SLS'
    ULS = 'ULS'
    FLS = 'FLS'
    ALS = 'ALS'


class LoadAxes(Enum):
    global_ = 'global'
    local = 'local'


class LoadCaseFactor(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    factor: float
    load_case_id: conint(ge=0)


class LoadCombination(BaseModel):
    check: str
    id: conint(ge=0)
    limit_state: LimitState | None = None
    load_case_factors: list[LoadCaseFactor] = Field(..., min_length=1)
    name: str
    situation: str | None = None


class LoadType(Enum):
    force = 'force'
    moment = 'moment'


class MassFormulation(Enum):
    CONSISTENT = 'CONSISTENT'
    LUMPED = 'LUMPED'


class MaterialProperty(Enum):
    E = 'E'
    G = 'G'
    Fy = 'Fy'
    Density = 'Density'


class MemberEndOffset(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    X: float | None = None
    Y: float | None = None
    Z: float | None = None


class MemberForceComponent(Enum):
    N = 'N'
    Vy = 'Vy'
    Vz = 'Vz'
    Mx = 'Mx'
    My = 'My'
    Mz = 'Mz'
    Bimoment = 'Bimoment'


class MemberId(RootModel[conint(ge=0)]):
    root: conint(ge=0)


class MemberSet(BaseModel):
    buckling_length_y: float | None = Field(
        None,
        description='Buckling-length overrides for code checks (EN 1993-1-1 §6.3). When absent,\nthe unity-check evaluator derives L_cr from `buckling_restraints` spacing.\nExplicit lengths (m) take precedence over the factors.',
    )
    buckling_length_z: float | None = None
    buckling_restraints: list[BucklingRestraint] | None = Field(
        [],
        description='Node-based buckling restraints along the beam (replaces scalar l_y/l_z).',
        validate_default=True,
    )
    classification: str | None = Field(
        None,
        description='Free-text label for the modeler/UI (e.g. "Upright", "Beam"); not used by\nthe solver.',
    )
    effective_length_factor_y: float | None = Field(
        None,
        description='Effective-length factor K_y (L_cr,y = K_y · L) when no explicit length given.',
    )
    effective_length_factor_z: float | None = None
    id: conint(ge=0)
    ltb_length: float | None = Field(
        None, description='Unrestrained length for lateral-torsional buckling (m).'
    )
    member_ids: list[MemberId] = Field(
        ...,
        description='Ids of the members (in `FERS.members`) that make up this beam.',
        min_length=1,
    )


class Point(RootModel[tuple[float, float]]):
    root: tuple[float, float]


class MemberStiffnessCurveDriver(Enum):
    N = 'N'
    Vy = 'Vy'
    Vz = 'Vz'
    Mx = 'Mx'
    My = 'My'
    Mz = 'Mz'


class MemberType(Enum):
    Normal = 'Normal'
    Truss = 'Truss'
    Tension = 'Tension'
    Compression = 'Compression'
    Rigid = 'Rigid'
    Cable = 'Cable'


class ModalAnalysisSettings(BaseModel):
    mass_formulation: MassFormulation | None = Field(
        None,
        description='Mass-matrix formulation (Consistent default, Lumped optional).',
    )
    max_iterations: conint(ge=0) | None = Field(
        None,
        description='Maximum subspace-iteration sweeps. Defaults to 100 when omitted.',
    )
    num_modes: conint(ge=1) = Field(
        ..., description='Number of natural modes (lowest frequencies) to extract.'
    )
    tolerance: float | None = Field(
        None,
        description='Eigen convergence tolerance (relative change in the tracked eigenvalues\nbetween subspace sweeps). Defaults to 1e-6 when omitted.',
    )


class ModalCombination(Enum):
    CQC = 'CQC'
    SRSS = 'SRSS'


class Node(BaseModel):
    X: float
    Y: float
    Z: float
    id: conint(ge=0)
    nodal_support: conint(ge=0) | None = None


class NodeDisplacement(BaseModel):
    dx: float
    dy: float
    dz: float
    rx: float
    ry: float
    rz: float
    warp: float | None = None


class NodeForces(BaseModel):
    bw: float | None = None
    fx: float
    fy: float
    fz: float
    mx: float
    my: float
    mz: float


class NodeLocation(BaseModel):
    X: float
    Y: float
    Z: float


class NonlinearMethod(Enum):
    P_DELTA = 'P_DELTA'
    COROTATIONAL = 'COROTATIONAL'


class OrthotropicPlateMaterial(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    e_x: PositiveFloat = Field(..., description="Young's modulus along local x.")
    e_y: PositiveFloat = Field(..., description="Young's modulus along local y.")
    g_xy: PositiveFloat = Field(..., description='In-plane shear modulus.')
    g_xz: float | None = Field(
        None,
        description='Transverse shear modulus (x–z); used by Mindlin/thick plates.',
    )
    g_yz: float | None = Field(
        None,
        description='Transverse shear modulus (y–z); used by Mindlin/thick plates.',
    )
    nu_xy: float = Field(
        ...,
        description="Major Poisson's ratio (ν_xy); ν_yx is derived from `e_x·ν_yx = e_y·ν_xy`.",
    )


class PathCommand(Enum):
    moveTo = 'moveTo'
    lineTo = 'lineTo'
    arcTo = 'arcTo'
    closePath = 'closePath'


class PdeltaFormulation(Enum):
    CONSISTENT = 'CONSISTENT'
    SIMPLIFIED = 'SIMPLIFIED'


class PdeltaMode(Enum):
    FULL = 'FULL'
    IN_PLANE_ONLY = 'IN_PLANE_ONLY'


class PlaneState(Enum):
    PlaneStress = 'PlaneStress'
    PlaneStrain = 'PlaneStrain'


class PlateBehavior(Enum):
    Shell = 'Shell'
    Membrane = 'Membrane'


class NodeId(RootModel[conint(ge=0)]):
    root: conint(ge=0)


class PlateElementShape(Enum):
    Auto = 'Auto'
    Triangle = 'Triangle'
    Quad = 'Quad'


class PlateMeshDivisions(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    u: conint(ge=1)
    v: conint(ge=1)


class PlateMeshMethod(Enum):
    Auto = 'Auto'
    Structured = 'Structured'
    Unstructured = 'Unstructured'


class PlateMeshSettings(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    divisions: PlateMeshDivisions | None = None
    element_shape: PlateElementShape | None = 'Auto'
    method: PlateMeshMethod | None = 'Auto'
    target_size: PositiveFloat | None = Field(
        None,
        description='Target element edge length. `None` meshes the boundary as-is (no interior\nrefinement).',
    )


class BoundaryNodeId(RootModel[conint(ge=0)]):
    root: conint(ge=0)


class PlateOpening(BaseModel):
    boundary_node_ids: list[BoundaryNodeId] = Field(
        ..., description='Hole boundary (≥ 3 existing model nodes).', min_length=3
    )
    id: conint(ge=0)


class Kind(Enum):
    Surface = 'Surface'


class PlatePressureTarget1(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    kind: Kind
    surface_id: conint(ge=0)


class Kind1(Enum):
    Element = 'Element'


class PlatePressureTarget2(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    kind: Kind1
    plate_element_id: conint(ge=0)


class PlatePressureTarget(RootModel[PlatePressureTarget1 | PlatePressureTarget2]):
    root: PlatePressureTarget1 | PlatePressureTarget2 = Field(
        ...,
        description='The target of a [`PlatePressure`]. A tagged union so exactly one target kind\nis set (replaces the previous pair of nullable ids).',
    )


class PlateResultants(BaseModel):
    mx: float
    mxy: float
    my: float
    nx: float
    nxy: float
    ny: float
    qx: float
    qy: float


class PlateStiffnessModifiers(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    bending: confloat(ge=0.0) | None = None
    membrane: confloat(ge=0.0) | None = None
    shear: confloat(ge=0.0) | None = None


class PlateStressMeasure(Enum):
    VonMises = 'VonMises'
    PrincipalMax = 'PrincipalMax'
    PrincipalMin = 'PrincipalMin'


class PlateTheory(Enum):
    Auto = 'Auto'
    Mindlin = 'Mindlin'
    Kirchhoff = 'Kirchhoff'


class PressureUnit(Enum):
    Pa = 'Pa'
    kPa = 'kPa'
    MPa = 'MPa'
    GPa = 'GPa'


class MemberForce(BaseModel):
    aggregation: Aggregation | None = None
    component: MemberForceComponent


class QuantitySource1(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    MemberForce_1: MemberForce = Field(
        ...,
        alias='MemberForce',
        description="A local member force, reduced by `aggregation` and enveloped over the\ncheck's applicable load combinations.",
    )


class Displacement(BaseModel):
    component: DispComponent


class QuantitySource2(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    Displacement_1: Displacement = Field(
        ...,
        alias='Displacement',
        description='A nodal displacement of the entity (member end / governing node).',
    )


class Material1(BaseModel):
    property: MaterialProperty


class QuantitySource4(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    Material: Material1 = Field(..., description="A property of the entity's material.")


class Geometry(BaseModel):
    property: GeometryProperty


class QuantitySource5(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    Geometry_1: Geometry = Field(
        ..., alias='Geometry', description='A geometric quantity of the entity.'
    )


class PlateStress(BaseModel):
    measure: PlateStressMeasure


class QuantitySource6(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    PlateStress_1: PlateStress = Field(
        ...,
        alias='PlateStress',
        description='A plate-element stress measure (for plate-targeted checks).',
    )


class QuantitySource7(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    Constant: float = Field(
        ...,
        description="A literal constant (in the model's units for its intended dimension).",
    )


class ReactionNodeResult(BaseModel):
    location: NodeLocation
    nodal_forces: NodeForces
    support_id: conint(ge=0)


class DirectParameters(BaseModel):
    ag: float
    beta: float | None = None
    q: float
    s: float
    tb: float
    tc: float
    td: float


class ResponseSpectrum2(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    DirectParameters_1: DirectParameters = Field(
        ...,
        alias='DirectParameters',
        description='Direct spectrum parameters (no preset lookup); national-annex agnostic.',
    )


class CustomPoints(BaseModel):
    points: list[list[float]]


class ResponseSpectrum3(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    CustomPoints_1: CustomPoints = Field(
        ...,
        alias='CustomPoints',
        description='Arbitrary `(period, spectral_acceleration)` table [s, m/s²], linearly\ninterpolated (clamped beyond the ends).',
    )


class ResultType1(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    Loadcase: conint(ge=0)


class ResultType2(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    Loadcombination: conint(ge=0)


class ResultType(RootModel[ResultType1 | ResultType2]):
    root: ResultType1 | ResultType2


class ResultsSummary(BaseModel):
    total_displacements: conint(ge=0)
    total_member_forces: conint(ge=0)
    total_plate_forces: conint(ge=0) | None = None
    total_reaction_forces: conint(ge=0)


class RigidStrategy(Enum):
    LinearMpc = 'LinearMpc'
    RigidMember = 'RigidMember'


class Section(BaseModel):
    a_sy: float | None = Field(
        None,
        description='Effective shear area in Y-direction (m²). None = no shear deformation (Euler-Bernoulli).',
    )
    a_sz: float | None = Field(
        None,
        description='Effective shear area in Z-direction (m²). None = no shear deformation (Euler-Bernoulli).',
    )
    area: PositiveFloat
    b: float | None = None
    centroid_y: float | None = Field(
        None,
        description='Centroid Y-coordinate within the shape path coordinate system (mm).\nUsed by the viewer to offset shape-path extrusions so the centroid\naligns with the member node.  Not used by the solver.',
    )
    centroid_z: float | None = Field(
        None,
        description='Centroid Z-coordinate within the shape path coordinate system (mm).',
    )
    ec3: Ec3SectionParams | None = None
    h: float | None = None
    i_w: float | None = Field(
        None,
        description='Warping constant (m⁶). None = no warping (pure St. Venant torsion).',
    )
    i_y: PositiveFloat
    i_yz: float | None = Field(
        None,
        description='Product of inertia about centroidal axes (mm⁴ in JSON, scaled to m⁴ by solver).\nNon-zero for asymmetric sections (e.g. angle, C-channel with unequal flanges).\nWhen present and non-zero, the solver auto-detects whether `i_y`/`i_z`\nare centroidal or principal values (by checking angle consistency) and\napplies or skips the principal-axis rotation accordingly.',
    )
    i_z: PositiveFloat
    id: conint(ge=0)
    j: PositiveFloat
    material: conint(ge=0)
    name: str
    principal_axis_angle: float | None = Field(
        None,
        description='Angle (degrees) from centroidal to principal axes.\nWhen `i_yz` is absent or zero, this angle is used to rotate the\nstiffness matrix from principal to centroidal frame.  When `i_yz`\nis present, the solver checks whether `i_y`/`i_z` are centroidal\n(angle matches formula) or principal (rotation applied).\nPositive = counter-clockwise.  Default 0.',
    )
    shape_path: conint(ge=0) | None = None
    wagner_coeff: float | None = Field(
        None, description='Wagner coefficient for lateral-torsional buckling.'
    )
    wel_y: PositiveFloat | None = Field(
        None,
        description='Elastic section modulus about the y (major) axis (m³). Universal property\n(≡ AISC `S_x`); used by unity checks for bending capacity.',
    )
    wel_z: PositiveFloat | None = Field(
        None, description='Elastic section modulus about the z (minor) axis (m³).'
    )
    wpl_y: PositiveFloat | None = Field(
        None,
        description='Plastic section modulus about the y (major) axis (m³, ≡ AISC `Z_x`).',
    )
    wpl_z: PositiveFloat | None = Field(
        None, description='Plastic section modulus about the z (minor) axis (m³).'
    )
    y_s: float | None = Field(
        None, description='Shear center Y-coordinate relative to centroid (m).'
    )
    z_s: float | None = Field(
        None, description='Shear center Z-coordinate relative to centroid (m).'
    )


class SectionForce(BaseModel):
    forces: NodeForces
    x_frac: float


class SectionProperty(Enum):
    Area = 'Area'
    Iy = 'Iy'
    Iz = 'Iz'
    J = 'J'
    Iw = 'Iw'
    WelY = 'WelY'
    WelZ = 'WelZ'
    WplY = 'WplY'
    WplZ = 'WplZ'
    H = 'H'
    B = 'B'
    Asy = 'Asy'
    Asz = 'Asz'


class SeismicDirection(Enum):
    X = 'X'
    Y = 'Y'
    Z = 'Z'


class SeismicMassSource(BaseModel):
    load_case_id: conint(ge=0)
    psi: float = Field(
        ...,
        description='Combination factor `ψE` (EN 1998-1 §3.2.4 / §4.2.4). Use 1.0 for permanent loads.',
    )


class SeismicMethod(Enum):
    MODAL_RESPONSE_SPECTRUM = 'MODAL_RESPONSE_SPECTRUM'
    LATERAL_FORCE = 'LATERAL_FORCE'
    BOTH = 'BOTH'


class SeismicModeContribution(BaseModel):
    base_shear: float = Field(
        ..., description='Modal base shear `Γ²·Sd(T)` (force units).'
    )
    effective_mass: float = Field(..., description='Effective modal mass `Γ²` (kg).')
    effective_mass_ratio: float = Field(
        ..., description='Effective modal mass / total seismic mass in this direction.'
    )
    mode: conint(ge=0)
    participation_factor: float = Field(
        ...,
        description='Modal participation factor `Γ = φ̂ᵀ·M·r` for this direction (mass-normalized `φ̂`).',
    )
    period: float = Field(..., description='Natural period `T = 2π/ω` (s).')
    spectral_acceleration: float = Field(
        ..., description='Design spectral acceleration `Sd(T)` (m/s²).'
    )


class ShapeCommand(BaseModel):
    center_y: float | None = None
    center_z: float | None = None
    command: PathCommand
    r: float | None = None
    theta0: float | None = None
    theta1: float | None = None
    y: float | None = None
    z: float | None = None


class ShapePath(BaseModel):
    id: conint(ge=0)
    name: str
    shape_commands: list[ShapeCommand]


class SolverMessage(BaseModel):
    code: str
    message: str


class SpectrumType(Enum):
    TYPE1 = 'TYPE1'
    TYPE2 = 'TYPE2'


class SupportConditionType(Enum):
    Fixed = 'Fixed'
    Free = 'Free'
    Spring = 'Spring'
    PositiveOnly = 'PositiveOnly'
    NegativeOnly = 'NegativeOnly'


class SupportForceComponent(Enum):
    Fx = 'Fx'
    Fy = 'Fy'
    Fz = 'Fz'
    Mx = 'Mx'
    My = 'My'
    Mz = 'Mz'


class SupportStiffnessCurve(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    depends_on: SupportForceComponent = Field(
        ..., description='Which global reaction component the stiffness depends on.'
    )
    points: list[Point] = Field(
        ...,
        description='Sorted `[force_value, stiffness]` pairs (≥ 2 points, positive stiffness).',
        min_length=2,
    )
    signed: bool | None = Field(
        None,
        description='When `true`, the curve is driven by the SIGNED reaction, so tension and\ncompression can have different stiffness (points may span negative\nforce). When `false` (default), the curve is driven by `|force|`\n(symmetric — the legacy behaviour).',
    )


class SurfaceLoadVertex(BaseModel):
    X: float
    Y: float
    Z: float


class UnitSystem(Enum):
    metric = 'metric'
    imperial = 'imperial'


class UnityStatus(Enum):
    Green = 'Green'
    Yellow = 'Yellow'
    Orange = 'Orange'
    Red = 'Red'


class VarSource2(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    Expression: str = Field(
        ...,
        description='An expression string (may reference earlier variable names + functions).',
    )


class Vector3(RootModel[tuple[float, float, float]]):
    root: tuple[float, float, float] = Field(
        ...,
        description='A 3-component vector `[x, y, z]`.\n\nShared schema referenced (via `#[schema(value_type = Vector3)]`) by every\ndirection/axis field so the OpenAPI defines one reusable component instead of\nrepeating the inline array. The Rust model keeps plain `(f64, f64, f64)`\ntuples and the JSON shape is unchanged.',
    )


class WorkAxis(BaseModel):
    direction_x: float
    direction_y: float
    direction_z: float
    id: conint(ge=0)
    name: str | None = None
    origin_x: float
    origin_y: float
    origin_z: float


class WorkPlane(BaseModel):
    id: conint(ge=0)
    name: str | None = None
    normal_x: float
    normal_y: float
    normal_z: float
    origin_x: float
    origin_y: float
    origin_z: float


class Workspace(BaseModel):
    entity_groups: list[EntityGroup] | None = Field(
        [],
        description='Generic, calculation-agnostic entity groups for UI/visualization.',
        validate_default=True,
    )
    work_axes: list[WorkAxis] | None = Field([], validate_default=True)
    work_planes: list[WorkPlane] | None = Field([], validate_default=True)


class AnalysisOptions(BaseModel):
    axial_slack: float | None = None
    dimensionality: Dimensionality
    enable_self_weight: bool | None = Field(
        False,
        description='When true, the engine generates self-weight (dead load) for every member\nfrom its material density and cross-sectional area, collected into a\nself-weight load case (see `self_weight_load_case_id`).  Cable members\ncarry their weight intrinsically in the catenary formulation and are\ntherefore excluded from the generated self-weight load.',
    )
    gravity_direction: Vector3 | None = Field(
        [0.0, -1.0, 0.0],
        description='Global gravity direction as a vector (normalized to a unit vector at use).\nDefault `(0, -1, 0)` — gravity acting in the negative Y direction.',
        validate_default=True,
    )
    gravity_factor: float | None = Field(
        -9.81,
        description='Signed gravitational acceleration magnitude in length-units/s².\nDefault `-9.81` (m/s²).  Self-weight per unit length is\n`w = density · area · |gravity_factor|` applied along `gravity_direction`.',
    )
    include_report_html: bool | None = Field(
        False,
        description='When true, the solver embeds the single consolidated unity-check HTML\nreport in `results.report_html`. Default false (keeps results JSON lean;\nthe CLI `--report` flag writes the report to a file instead).',
    )
    include_shear_center_coupling: bool | None = Field(
        True,
        description='When false, suppresses shear-center eccentricity coupling (T^T·K·T\ntransformation) by clearing y_s/z_s for all sections.  Some commercial\nsolvers do not apply this coupling; disabling it improves agreement.',
    )
    include_shear_deformation: bool | None = Field(
        True,
        description='When false, forces shear deformation factor φ=0 (Euler-Bernoulli) for all elements.',
    )
    include_warping: bool | None = Field(
        True,
        description='When false, ignores warping constant Iw and uses pure GJ/L torsion for all elements.',
    )
    max_iterations: conint(ge=0) | None = None
    nonlinear_method: NonlinearMethod | None = Field(
        None,
        description='Controls the nonlinear solver formulation (P_DELTA or COROTATIONAL).\nOnly affects second-order (nonlinear) analysis.',
    )
    order: AnalysisOrder
    pdelta_formulation: PdeltaFormulation | None = Field(
        None,
        description='Controls the geometric stiffness matrix formulation for P-Delta analysis.\n`Consistent` (default) uses full Przemieniecki K_g; `Simplified` uses\nP/L-only diagonal terms matching commercial solvers.',
    )
    pdelta_mode: PdeltaMode | None = Field(
        None,
        description="High-level P-Delta strategy.  `Full` (default) amplifies all directions.\n`InPlaneOnly` auto-detects the out-of-plane axis from the model's\nbounding box and suppresses it, matching commercial solver behavior.\nOverrides `pdelta_suppress_axes` when set to `InPlaneOnly`.",
    )
    pdelta_suppress_axes: list[str] | None = Field(
        None,
        description='Global translational axes to exclude from P-Delta amplification.\n\nWhen a structure is near buckling in an out-of-plane direction,\nthe consistent P-Delta amplification can produce forces that differ\nsignificantly from commercial solvers which\ntypically only amplify in-plane sway.\n\nSet to `["Z"]` for in-plane racks/portal frames where Z is out-of-plane,\nor `["X","Z"]` to limit P-Delta to Y-sway only.  Empty (default) means\nall translational directions are amplified.\n\nMaps to global DOFs: "X"→0,7  "Y"→1,8  "Z"→2,9  per element.',
    )
    render_unity_reports: bool | None = Field(
        False,
        description="When true, fill each unity check's per-entity `rendered_report` from its\n`report_template` (rendered against the entity's computed trace). Default\nfalse for speed; orthogonal to `include_report_html` — narratives appear in\nthe consolidated HTML only when this is also true.",
    )
    rigid_strategy: RigidStrategy
    self_weight_load_case_id: conint(ge=0) | None = Field(
        None,
        description='Target load case id that generated self-weight loads are injected into.\nWhen set, the loads are added to that (typically empty "G") load case so\ncombinations can factor it (e.g. 1.35·G).  When `None` and self-weight is\nenabled, a new load case is created automatically.',
    )
    solve_loadcases: bool
    tolerance: float


class BucklingAnalysisSettings(BaseModel):
    max_iterations: conint(ge=0) | None = Field(
        None,
        description='Maximum subspace-iteration sweeps. Defaults to 100 when omitted.',
    )
    num_modes: conint(ge=1) = Field(
        ...,
        description='Number of buckling modes (lowest positive critical factors) to extract.',
    )
    reference: EigenLoadRef = Field(
        ...,
        description='Reference load whose first-order stress state drives the geometric\nstiffness `K_g`.',
    )
    tolerance: float | None = Field(
        None,
        description='Eigen convergence tolerance (relative change in the tracked eigenvalues\nbetween subspace sweeps). Defaults to 1e-6 when omitted.',
    )


class BucklingMode(BaseModel):
    critical_load_factor: float = Field(
        ...,
        description='Critical load factor `α_cr = λ`. The structure buckles when the reference\nload is scaled by this factor (EN 1993-1-1 §5.2.1).',
    )
    displacements: dict[constr(pattern=r'^[0-9]+$'), NodeDisplacement] = Field(
        ...,
        description='Buckling mode shape: per-node displacement pattern (normalized so the\nlargest translational component is 1).',
    )
    mode: conint(ge=0) = Field(
        ..., description='1-based mode number (1 = lowest critical load factor).'
    )


class BucklingResults(BaseModel):
    modes: list[BucklingMode]


class DistributedLoad(BaseModel):
    direction: Vector3
    end_frac: confloat(ge=0.0, le=1.0)
    end_magnitude: float
    id: conint(ge=0)
    magnitude: float
    member: conint(ge=0)
    start_frac: confloat(ge=0.0, le=1.0)


class Ec3SteelSpec(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    c1: float | None = Field(
        None,
        description="LTB moment-distribution factor C1. When omitted it is computed from the\nmember's actual moment diagram (NCCI SN003 quarter-point formula); set it\nexplicitly to override (e.g. 1.0 = conservative uniform moment).",
    )
    c2: float | None = Field(
        0.0,
        description='LTB factors C2 / C3 for the general `M_cr` (load height / mono-symmetry).\nDefault 0.0 → the doubly-symmetric form (no load-height or z_j term).',
    )
    c3: float | None = 0.0
    gamma_m0: float | None = 1.0
    gamma_m1: float | None = 1.0
    include_buckling: bool | None = True
    include_ltb: bool | None = True
    interaction_method: InteractionMethod | None = None
    z_g: float | None = Field(
        0.0,
        description='Transverse-load application height `z_g` above the shear centre (model\nlength units). Positive = destabilising (load above shear centre).\nDefault 0.0 (load at the shear centre).',
    )


class EntityUnityResult(BaseModel):
    capacity: float | None = None
    demand: float
    entity: EntityRef
    governing_combination_id: conint(ge=0) | None = None
    location_x_frac: confloat(ge=0.0, le=1.0) | None = None
    message: str | None = None
    rendered_report: str | None = Field(
        None,
        description="Rendered narrative report (from the check's `report_template`), if any.",
    )
    status: UnityStatus
    trace: list[CalcStep] | None = Field(
        [],
        description='Transparent hand-calc trace (symbolic + substituted) in display units.',
        validate_default=True,
    )
    utilization: float


class ErrorsAndWarnings(BaseModel):
    errors: list[SolverMessage] | None = Field([], validate_default=True)
    warnings: list[SolverMessage] | None = Field([], validate_default=True)


class Material(BaseModel):
    density: PositiveFloat
    e_mod: PositiveFloat
    g_mod: PositiveFloat
    id: conint(ge=0)
    name: str
    orthotropic_plate: OrthotropicPlateMaterial | None = None
    yield_stress: float


class Member(BaseModel):
    chi: float | None = Field(
        None,
        description="Optional user-supplied buckling reduction factor χ (EN 1993-1-1 §6.3).\nCurrently informational: the EC3 unity-check evaluator computes its own χ\nfrom the section's buckling curve and does not yet read this override.",
    )
    classification: str | None = Field(
        None,
        description='Free-text grouping key used to target this member in unity checks\n(`EntitySelector::MemberClassification`). `None` = unclassified.',
    )
    end_hinge: conint(ge=0) | None = None
    end_node_id: conint(ge=0)
    end_offset: MemberEndOffset | None = None
    id: conint(ge=0)
    member_type: MemberType
    mirror: bool | None = Field(
        None,
        description='When true, the cross-section is mirrored: shear-center offsets y_s and\nz_s are negated, and the shape_path geometry is flipped.',
    )
    pretension: float | None = Field(
        None,
        description='Initial cable tension (force units) for `Cable` members. Used to derive\nthe unstretched length when `unstretched_length` is not given directly:\n`L₀ = L_chord / (1 + pretension/EA)`.  Ignored for non-cable members.',
    )
    reference_member: conint(ge=0) | None = Field(
        None,
        description="Reference member used by the modeler/UI to define this member's orientation\nor grouping. Not used by the solver; preserved for consumers/unity checks.",
    )
    reference_node: conint(ge=0) | None = Field(
        None,
        description='Reference node used by the modeler/UI (e.g. orientation reference). Not used\nby the solver; preserved for consumers/unity checks.',
    )
    rotation_angle: float
    section: conint(ge=0) | None = None
    start_hinge: conint(ge=0) | None = None
    start_node_id: conint(ge=0)
    start_offset: MemberEndOffset | None = None
    unstretched_length: float | None = Field(
        None,
        description="Explicit unstretched (natural) length L₀ (length units) for `Cable`\nmembers.  Takes precedence over `pretension`.  When neither is set, the\ncable's unstretched length defaults to the straight chord length.",
    )
    weight: float = Field(
        ...,
        description='Optional self-weight override as a gravity load **per unit length**, in the\nmodel\'s force/length units (already including g). When non-zero it replaces\nthe computed `density · area · g` self-weight for this member (see\n`append_self_weight_loads`); `0.0` means "use the computed value".',
    )


class MemberPointLoad(BaseModel):
    axes: LoadAxes | None = Field(
        'global', description='Coordinate frame the `direction` is expressed in.'
    )
    direction: Vector3 = Field(
        ..., description='Load direction unit vector (global or local axes).'
    )
    id: conint(ge=0)
    magnitude: float
    member: conint(ge=0)
    position: confloat(ge=0.0, le=1.0) = Field(
        ...,
        description='Fractional position along the member (0.0 = start, 1.0 = end).',
    )


class MemberPointMoment(BaseModel):
    axes: LoadAxes | None = Field(
        'global', description='Coordinate frame the `direction` is expressed in.'
    )
    direction: Vector3 = Field(
        ..., description='Load direction unit vector (global or local axes).'
    )
    id: conint(ge=0)
    magnitude: float
    member: conint(ge=0)
    position: confloat(ge=0.0, le=1.0) = Field(
        ...,
        description='Fractional position along the member (0.0 = start, 1.0 = end).',
    )


class MemberResult(BaseModel):
    end_node_forces: NodeForces
    local_displacement_end_node: NodeDisplacement
    local_displacement_start_node: NodeDisplacement
    local_end_forces: NodeForces
    local_maximums: NodeForces
    local_minimums: NodeForces
    local_start_forces: NodeForces
    maximums: NodeForces
    minimums: NodeForces
    section_forces: list[SectionForce]
    start_node_forces: NodeForces


class MemberStiffnessCurve(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    depends_on: MemberStiffnessCurveDriver = Field(
        ..., description='Which member-local force component the stiffness depends on.'
    )
    points: list[Point] = Field(
        ...,
        description='Sorted `[force_value, stiffness]` pairs (≥ 2 points, positive stiffness).',
        min_length=2,
    )
    signed: bool | None = Field(
        None,
        description='When `true`, the curve is driven by the SIGNED force, so tension and\ncompression can have different stiffness (points may span negative\nforce). When `false` (default), the curve is driven by `|force|`\n(symmetric in tension/compression — the legacy behaviour).',
    )


class ModeShape(BaseModel):
    angular_frequency: float = Field(..., description='Angular frequency `ω` (rad/s).')
    displacements: dict[constr(pattern=r'^[0-9]+$'), NodeDisplacement] = Field(
        ...,
        description='Mode shape: per-node displacement pattern (normalized so the largest\ntranslational component is 1).',
    )
    effective_mass: list[float] = Field(
        ...,
        description='Effective modal mass per global direction `[X, Y, Z, RX, RY, RZ]`\n(`Γ² / (φᵀ·M·φ)`, in kg). The sum across modes approaches the total\nfree mass of the structure in each direction.',
    )
    eigenvalue: float = Field(..., description='Eigenvalue `ω²` (rad²/s²).')
    modal_mass: float = Field(
        ...,
        description='Generalized (modal) mass `φᵀ·M·φ` (kg) for the reported, max-translation\nnormalized shape.',
    )
    mode: conint(ge=0) = Field(
        ..., description='1-based mode number (1 = lowest frequency).'
    )
    natural_frequency: float = Field(
        ..., description='Natural frequency `f = ω / 2π` (Hz).'
    )
    participation_factors: list[float] = Field(
        ...,
        description='Modal participation factor per global direction\n`[X, Y, Z, RX, RY, RZ]` (`Γ = φᵀ·M·r`).',
    )
    period: float = Field(..., description='Period `T = 1 / f` (s).')


class NodalLoad(BaseModel):
    direction: Vector3
    id: conint(ge=0)
    load_type: LoadType
    magnitude: float
    node: conint(ge=0)


class NodalMoment(BaseModel):
    direction: Vector3
    id: conint(ge=0)
    load_type: LoadType
    magnitude: float
    node: conint(ge=0)


class PlateElement(BaseModel):
    behavior: PlateBehavior | None = 'Shell'
    id: conint(ge=0)
    local_x_direction: Vector3 | None = None
    material: conint(ge=0)
    node_ids: list[NodeId] = Field(
        ...,
        description='Element connectivity: 3 nodes (triangle) or 4 nodes (quad).',
        max_length=4,
        min_length=3,
    )
    offset: float | None = Field(
        0.0,
        description='Distance from the reference surface along the local plate normal.',
    )
    plane_state: PlaneState | None = Field(
        'PlaneStress',
        description='In-plane constitutive assumption (plane stress/strain).',
    )
    source_surface_id: conint(ge=0) | None = Field(
        None, description='The `PlateSurface` this element was meshed from, if any.'
    )
    stiffness_modifiers: PlateStiffnessModifiers | None = None
    theory: PlateTheory | None = Field(
        'Auto', description='Finite-element theory (thin/thick/auto).'
    )
    thickness: PositiveFloat


class PlatePressure(BaseModel):
    direction: Vector3
    id: conint(ge=0)
    magnitude: float
    projected: bool | None = Field(
        False,
        description='When true the pressure acts on the area projected onto `direction`\n(e.g. snow), otherwise on the true element area.',
    )
    target: PlatePressureTarget = Field(
        ...,
        description='What the pressure is applied to — exactly one of a surface or an element.',
    )


class PlateResult(BaseModel):
    centroid: NodeLocation
    centroid_displacement_global: NodeDisplacement
    centroid_displacement_local: NodeDisplacement
    nodal_forces_global: dict[constr(pattern=r'^[0-9]+$'), NodeForces]
    plate_id: conint(ge=0)
    resultants: PlateResultants


class PlateSurface(BaseModel):
    behavior: PlateBehavior | None = 'Shell'
    boundary_node_ids: list[BoundaryNodeId] = Field(
        ...,
        description='Outer boundary, referencing existing model nodes (counter-clockwise).',
        min_length=3,
    )
    classification: str | None = None
    generated_plate_element_ids: list[conint(ge=0)] | None = Field(
        [],
        description='Ids of the plate elements generated from this surface. Populated by the\nmesher; any input value is ignored (derived from element\n`source_surface_id`).',
    )
    id: conint(ge=0)
    local_x_direction: Vector3 | None = None
    material: conint(ge=0)
    mesh: PlateMeshSettings | None = None
    mesh_group_id: conint(ge=0) | None = Field(
        None,
        description='Surfaces sharing a `mesh_group_id` are meshed together so coincident\nboundary nodes are shared between them.',
    )
    name: str | None = None
    offset: float | None = Field(
        0.0,
        description='Distance from the reference surface along the local plate normal.',
    )
    openings: list[PlateOpening] | None = Field(
        [],
        description='Holes in the surface; the mesher generates elements around them.',
        validate_default=True,
    )
    plane_state: PlaneState | None = Field(
        'PlaneStress',
        description='In-plane constitutive assumption (plane stress/strain).',
    )
    stiffness_modifiers: PlateStiffnessModifiers | None = None
    theory: PlateTheory | None = Field(
        'Auto', description='Finite-element theory (thin/thick/auto).'
    )
    thickness: PositiveFloat


class Section1(BaseModel):
    property: SectionProperty


class QuantitySource3(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    Section: Section1 = Field(..., description="A property of the entity's section.")


class QuantitySource(
    RootModel[
        QuantitySource1
        | QuantitySource2
        | QuantitySource3
        | QuantitySource4
        | QuantitySource5
        | QuantitySource6
        | QuantitySource7
    ]
):
    root: (
        QuantitySource1
        | QuantitySource2
        | QuantitySource3
        | QuantitySource4
        | QuantitySource5
        | QuantitySource6
        | QuantitySource7
    ) = Field(
        ...,
        description='A bindable quantity — the source of a `{{variable}}` in a unity-check formula.',
    )


class EurocodeParametric(BaseModel):
    ag: float = Field(
        ...,
        description='Design ground acceleration on type-A ground, `a_g = γ_I·a_gR` [m/s²].',
    )
    beta: float | None = Field(
        None,
        description='Lower-bound factor `β` for the design spectrum (default 0.2).',
    )
    ground_type: GroundType
    q: float = Field(..., description='Behaviour factor `q` (≥ 1).')
    spectrum_type: SpectrumType


class ResponseSpectrum1(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    EurocodeParametric_1: EurocodeParametric = Field(
        ...,
        alias='EurocodeParametric',
        description='EN 1998-1 parametric: shape parameters (S, Tb, Tc, Td) are looked up from\nthe ground type + spectrum type, scaled by `ag` and the behaviour factor\n`q`.',
    )


class ResponseSpectrum(
    RootModel[ResponseSpectrum1 | ResponseSpectrum2 | ResponseSpectrum3]
):
    root: ResponseSpectrum1 | ResponseSpectrum2 | ResponseSpectrum3 = Field(
        ...,
        description='Design response spectrum definition. Externally tagged: exactly one of the\nthree variants.',
    )


class Results(BaseModel):
    displacement_nodes: dict[constr(pattern=r'^[0-9]+$'), NodeDisplacement]
    errors_and_warnings: ErrorsAndWarnings | None = Field(
        None,
        description='Solver diagnostics (errors/warnings) for this load case/combination.\nEmpty in the common case.',
    )
    member_results: dict[constr(pattern=r'^[0-9]+$'), MemberResult]
    name: str
    plate_results: dict[constr(pattern=r'^[0-9]+$'), PlateResult] | None = None
    reaction_nodes: dict[constr(pattern=r'^[0-9]+$'), ReactionNodeResult]
    result_type: ResultType
    summary: ResultsSummary


class SeismicAnalysisSettings(BaseModel):
    damping: float | None = Field(
        0.05,
        description='Viscous damping ratio `ξ` for the CQC correlation (default 0.05).',
    )
    directional_combination: DirectionalCombination | None = Field(
        None, description='Directional combination rule (default SRSS).'
    )
    directions: list[SeismicDirection] | None = Field(
        None, description='Excitation directions to analyze (default `[X, Y]`).'
    )
    include_structural_mass: bool | None = Field(
        True,
        description='Include structural self-mass (density·area + weight override) in the\nseismic mass. Default true.',
    )
    mass_formulation: MassFormulation | None = Field(
        None,
        description='Structural mass-matrix formulation (Consistent default, Lumped optional).',
    )
    mass_sources: list[SeismicMassSource] | None = Field(
        None, description='Gravity load cases converted to seismic mass (`ΣG + ψE·Q`).'
    )
    max_iterations: conint(ge=0) | None = Field(
        None, description='Maximum subspace-iteration sweeps (default 100).'
    )
    method: SeismicMethod
    modal_combination: ModalCombination | None = Field(
        None, description='Modal combination rule (default CQC).'
    )
    num_modes: conint(ge=1) = Field(
        ..., description='Number of vibration modes to extract for MRSA.'
    )
    spectrum_x: ResponseSpectrum = Field(
        ..., description='Design spectrum for the X excitation direction.'
    )
    spectrum_y: ResponseSpectrum | None = None
    spectrum_z: ResponseSpectrum | None = None
    tolerance: float | None = Field(
        None, description='Eigen convergence tolerance (default 1e-6).'
    )


class SeismicDirectionResult(BaseModel):
    base_shear: float = Field(
        ..., description='Combined base shear in this direction (force units).'
    )
    combined: Results = Field(
        ...,
        description='Combined response for this direction alone (before directional combination).',
    )
    direction: SeismicDirection
    modes: list[SeismicModeContribution] | None = Field(
        None, description='Per-mode contributions (empty for the lateral-force method).'
    )
    participating_mass_ratio: float = Field(
        ...,
        description='Σ effective modal mass / total mass — the EN 1998-1 §4.3.3.3.1(3) ≥0.90\ncheck (1.0 for the lateral-force method).',
    )
    total_seismic_mass: float = Field(
        ..., description='Total seismic mass excited in this direction (kg).'
    )


class SupportCondition(BaseModel):
    condition_type: SupportConditionType
    stiffness: float | None = None
    stiffness_curve: SupportStiffnessCurve | None = None


class SurfaceLoad(BaseModel):
    direction: Vector3
    distribution_direction: Vector3 | None = None
    id: conint(ge=0)
    magnitude: float
    polygon: list[SurfaceLoadVertex]


class SwayImperfection(BaseModel):
    axis: Vector3 = Field(
        ...,
        description='Rotation axis. The sway direction is `axis × height_direction`.',
    )
    height_direction: Vector3 | None = Field(
        None,
        description='Direction along which height is measured and which is never displaced\n(the structure\'s "up"). Defaults to global +Y.',
    )
    magnitude: float = Field(
        ..., description='Sway (lean) angle in **radians**, applied about `axis`.'
    )
    reference_point: Vector3 | None = Field(
        None,
        description="A point on the zero-sway plane: the lean is proportional to a node's\nheight above this point (along `height_direction`). Only a measurement\nreference, not a pivot. Defaults to the origin.",
    )


class TranslationImperfection(BaseModel):
    axis: Vector3
    magnitude: float
    memberset_ids: list[conint(ge=0)]


class UnitSettings(BaseModel):
    densityUnit: DensityUnit | None = None
    forceUnit: ForceUnit | None = None
    lengthUnit: LengthUnit | None = None
    pressureUnit: PressureUnit | None = None
    system: UnitSystem | None = None


class UnityCheckResult(BaseModel):
    check_id: str
    governing: EntityUnityResult | None = None
    limit_state: LimitState | None = None
    max_utilization: float
    name: str
    per_entity: list[EntityUnityResult] | None = Field([], validate_default=True)
    status: UnityStatus


class VarSource1(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    Quantity: QuantitySource


class VarSource(RootModel[VarSource1 | VarSource2]):
    root: VarSource1 | VarSource2 = Field(
        ...,
        description='The source of a named formula variable: a catalog quantity, or a\nsub-expression over previously-declared variables/quantities.',
    )


class CheckSpec2(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    Ec3Steel: Ec3SteelSpec


class ImperfectionCase(BaseModel):
    imperfection_case_id: conint(ge=0)
    load_combinations: list[conint(ge=0)]
    sway_imperfections: list[SwayImperfection]
    translation_imperfections: list[TranslationImperfection]


class LateralForceResults(BaseModel):
    combined: Results
    per_direction: list[SeismicDirectionResult]


class LoadCase(BaseModel):
    distributed_loads: list[DistributedLoad] | None = Field([], validate_default=True)
    id: conint(ge=0)
    member_point_loads: list[MemberPointLoad] | None = Field([], validate_default=True)
    member_point_moments: list[MemberPointMoment] | None = Field(
        [], validate_default=True
    )
    name: str
    nodal_loads: list[NodalLoad] | None = Field([], validate_default=True)
    nodal_moments: list[NodalMoment] | None = Field([], validate_default=True)
    plate_pressures: list[PlatePressure] | None = Field([], validate_default=True)
    surface_loads: list[SurfaceLoad] | None = Field([], validate_default=True)


class MemberHinge(BaseModel):
    hinge_type: str = Field(
        ...,
        description='Free-text label for human readability only (e.g. `"Column base"`,\n`"SPRING_YZ"`). The solver ignores this field — actual hinge behavior is\ndriven entirely by the release/stiffness fields below. Not a constrained\nvalue set, so intentionally a `String` rather than an enum.',
    )
    id: conint(ge=0)
    max_bimoment_warp: float | None = None
    max_moment_mx: float | None = None
    max_moment_my: float | None = None
    max_moment_mz: float | None = None
    max_tension_vx: float | None = None
    max_tension_vy: float | None = None
    max_tension_vz: float | None = None
    rotational_release_mx: float | None = None
    rotational_release_my: float | None = None
    rotational_release_mz: float | None = None
    rotational_release_warp: float | None = None
    stiffness_curve_mx: MemberStiffnessCurve | None = None
    stiffness_curve_my: MemberStiffnessCurve | None = None
    stiffness_curve_mz: MemberStiffnessCurve | None = None
    stiffness_curve_vx: MemberStiffnessCurve | None = None
    stiffness_curve_vy: MemberStiffnessCurve | None = None
    stiffness_curve_vz: MemberStiffnessCurve | None = None
    translational_release_vx: float | None = None
    translational_release_vy: float | None = None
    translational_release_vz: float | None = None


class ModalResults(BaseModel):
    modes: list[ModeShape]


class MrsaResults(BaseModel):
    combined: Results = Field(
        ..., description='Final envelope after directional combination.'
    )
    per_direction: list[SeismicDirectionResult] = Field(
        ...,
        description='Per excitation direction (base shear, modal-mass table, per-direction envelope).',
    )


class NodalSupport(BaseModel):
    RX: SupportCondition | None = None
    RY: SupportCondition | None = None
    RZ: SupportCondition | None = None
    X: SupportCondition | None = None
    Y: SupportCondition | None = None
    Z: SupportCondition | None = None
    classification: str | None = Field(
        None, description='Free-text label for the modeler/UI; not used by the solver.'
    )
    id: conint(ge=0)
    warping_condition: SupportCondition | None = None


class SeismicResults(BaseModel):
    lateral_force: LateralForceResults | None = None
    modal_response_spectrum: MrsaResults | None = None


class Settings(BaseModel):
    general_info: GeneralInfo
    unit_settings: UnitSettings


class VarBinding(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    name: str
    source: VarSource


class GenericSpec(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    capacity: str = Field(
        ..., description='Capacity (resistance) expression, e.g. `"fy"`.'
    )
    demand: str = Field(
        ...,
        description='Demand (action effect) expression, e.g.\n`"bending_moment * fibre_distance / second_moment_of_area"`.',
    )
    variables: list[VarBinding] | None = Field(
        [],
        description="Named variables referenced by `demand`/`capacity` (and, via the computed\ntrace, by the check's `report_template`).",
        validate_default=True,
    )


class Model(BaseModel):
    materials: list[Material]
    member_hinges: list[MemberHinge] | None = Field([], validate_default=True)
    member_sets: list[MemberSet]
    members: list[Member] = Field(
        ...,
        description='Single source of truth for member objects. Member sets reference these by id.',
    )
    nodal_supports: list[NodalSupport]
    nodes: list[Node]
    plate_elements: list[PlateElement] | None = Field([], validate_default=True)
    plate_surfaces: list[PlateSurface] | None = Field([], validate_default=True)
    sections: list[Section]
    shape_paths: list[ShapePath] | None = Field([], validate_default=True)
    workspace: Workspace | None = Field({}, validate_default=True)


class ResultsBundle(BaseModel):
    buckling: BucklingResults | None = None
    loadcases: dict[str, Results]
    loadcombinations: dict[str, Results]
    modal: ModalResults | None = None
    report_html: str | None = Field(
        None,
        description='Optional single consolidated HTML report (populated only when requested\nvia the CLI `--report` flag or `AnalysisOptions.include_report_html`).',
    )
    seismic: SeismicResults | None = None
    unity_check_results: list[UnityCheckResult] | None = Field(
        [],
        description='Unity-check results (one entry per check definition), enveloped over the\napplicable load combinations.',
        validate_default=True,
    )


class CheckSpec1(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    Generic: GenericSpec


class CheckSpec(RootModel[CheckSpec1 | CheckSpec2]):
    root: CheckSpec1 | CheckSpec2 = Field(
        ...,
        description='The evaluator kind. Open union — new codes (AISC, …) add variants; the\nresult/report/colour layer is identical for every variant.',
    )


class UnityCheckDefinition(BaseModel):
    applies_to: EntitySelector
    description: str | None = None
    id: str
    limit_state: LimitState | None = None
    load_combination_ids: list[conint(ge=0)] | None = Field(
        [],
        description='Restrict to these combination ids (empty = all matching `limit_state`).',
    )
    name: str
    report_template: str | None = Field(
        None,
        description="Optional narrative report template (authored HTML/markdown). Placeholders are\nfilled from each entity's computed trace: `{{label}}` → that step's display\nstring (number + unit) and `{{= expr}}` → `expr` evaluated over the trace\nvalues (display units). Rendered into each `EntityUnityResult.rendered_report`\nonly when `analysis.options.render_unity_reports` is true.",
    )
    spec: CheckSpec
    thresholds: list[float] | None = Field(
        [0.8, 0.95, 1.0],
        description='Utilization colour boundaries [green→yellow, yellow→orange, orange→red].',
    )


class Analysis(BaseModel):
    buckling: BucklingAnalysisSettings | None = None
    imperfection_cases: list[ImperfectionCase] | None = Field([], validate_default=True)
    load_cases: list[LoadCase] | None = Field([], validate_default=True)
    load_combinations: list[LoadCombination] | None = Field([], validate_default=True)
    modal: ModalAnalysisSettings | None = None
    options: AnalysisOptions = Field(
        ...,
        description='Solver options (first/second order, tolerances, self-weight, gravity, …).',
    )
    seismic: SeismicAnalysisSettings | None = None
    unity_checks: list[UnityCheckDefinition] | None = Field(
        [],
        description='Post-processing unity checks evaluated against the results.',
        validate_default=True,
    )


class FERS(BaseModel):
    analysis: Analysis = Field(
        ...,
        description='The analysis definition: solver options + load/imperfection cases.',
    )
    model: Model = Field(
        ...,
        description='The structural model: geometry, topology, materials, workspace.',
    )
    results: ResultsBundle | None = None
    schema_version: conint(ge=0) | None = Field(
        2,
        description='Schema contract version (see [`SCHEMA_VERSION`]). Defaults to the current\nversion when omitted so older documents still parse.',
    )
    settings: Settings = Field(
        ...,
        description='Units + general info (analysis solver options live on `analysis.options`).',
    )
