# generated by datamodel-codegen:
#   filename:  openapi.json

from __future__ import annotations

from enum import Enum
from typing import Any

from pydantic import BaseModel, Field, RootModel, conint


class AnalysisOrder(Enum):
    LINEAR = "LINEAR"
    NONLINEAR = "NONLINEAR"


class DensityUnit(Enum):
    kg_m3 = "kg/m3"
    kg_mm3 = "kg/mm3"


class Dimensionality(Enum):
    field_2D = "2D"
    field_3D = "3D"


class DistributedLoad(BaseModel):
    direction: list[float] = Field(..., max_length=3)
    end_frac: float
    end_magnitude: float
    load_case: conint(ge=0)
    magnitude: float
    member: conint(ge=0)
    start_frac: float


class EntityGroup(BaseModel):
    id: conint(ge=0)
    member_ids: list[conint(ge=0)] | None = None
    member_set_ids: list[conint(ge=0)] | None = None
    name: str | None = None
    node_ids: list[conint(ge=0)] | None = None
    plate_ids: list[conint(ge=0)] | None = None
    support_ids: list[conint(ge=0)] | None = None
    work_axis_ids: list[conint(ge=0)] | None = None
    work_plane_ids: list[conint(ge=0)] | None = None


class ForceComponent(Enum):
    N = "N"
    Vy = "Vy"
    Vz = "Vz"
    Mx = "Mx"
    My = "My"
    Mz = "Mz"
    Fx = "Fx"
    Fy = "Fy"
    Fz = "Fz"


class ForceUnit(Enum):
    N = "N"
    kN = "kN"


class GeneralInfo(BaseModel):
    author: str
    project_name: str
    version: str


class GoverningKey(BaseModel):
    load_case_id: conint(ge=0) | None = None
    load_combination_id: conint(ge=0) | None = None
    member_id: conint(ge=0) | None = None


class LengthUnit(Enum):
    mm = "mm"
    cm = "cm"
    m = "m"


class LimitState(Enum):
    SLS = "SLS"
    ULS = "ULS"
    FLS = "FLS"
    ALS = "ALS"


class LoadCombination(BaseModel):
    check: str
    id: conint(ge=0)
    limit_state: LimitState | None = None
    load_cases_factors: dict[str, float]
    name: str
    situation: str | None = None


class Material(BaseModel):
    density: float
    e_mod: float
    g_mod: float
    id: conint(ge=0)
    name: str
    yield_stress: float


class MemberEndOffset(BaseModel):
    x: float | None = None
    y: float | None = None
    z: float | None = None


class MemberPointLoad(BaseModel):
    axes: str | None = Field(None, description='Coordinate axes: "global" or "local".')
    direction: list[float] = Field(
        ...,
        description="Load direction unit vector (global or local axes).",
        max_length=3,
    )
    id: conint(ge=0)
    load_case: conint(ge=0)
    magnitude: float
    member: conint(ge=0)
    position: float = Field(
        ...,
        description="Fractional position along the member (0.0 = start, 1.0 = end).",
    )


class MemberPointMoment(BaseModel):
    axes: str | None = Field(None, description='Coordinate axes: "global" or "local".')
    direction: list[float] = Field(
        ...,
        description="Load direction unit vector (global or local axes).",
        max_length=3,
    )
    id: conint(ge=0)
    load_case: conint(ge=0)
    magnitude: float
    member: conint(ge=0)
    position: float = Field(
        ...,
        description="Fractional position along the member (0.0 = start, 1.0 = end).",
    )


class MemberType(Enum):
    Normal = "Normal"
    Truss = "Truss"
    Tension = "Tension"
    Compression = "Compression"
    Rigid = "Rigid"
    Cable = "Cable"


class NodalLoad(BaseModel):
    direction: list[float] = Field(..., max_length=3)
    id: conint(ge=0)
    load_case: conint(ge=0)
    load_type: str
    magnitude: float
    node: conint(ge=0)


class NodalMoment(BaseModel):
    direction: list[float] = Field(..., max_length=3)
    id: conint(ge=0)
    load_case: conint(ge=0)
    load_type: str
    magnitude: float
    node: conint(ge=0)


class Node(BaseModel):
    X: float
    Y: float
    Z: float
    id: conint(ge=0)
    nodal_support: conint(ge=0) | None = None


class NodeDisplacement(BaseModel):
    dx: float
    dy: float
    dz: float
    rx: float
    ry: float
    rz: float
    warp: float | None = None


class NodeForces(BaseModel):
    bw: float | None = None
    fx: float
    fy: float
    fz: float
    mx: float
    my: float
    mz: float


class NodeLocation(BaseModel):
    X: float
    Y: float
    Z: float


class NonlinearMethod(Enum):
    P_DELTA = "P_DELTA"
    COROTATIONAL = "COROTATIONAL"


class PdeltaFormulation(Enum):
    CONSISTENT = "CONSISTENT"
    SIMPLIFIED = "SIMPLIFIED"


class PdeltaMode(Enum):
    FULL = "FULL"
    IN_PLANE_ONLY = "IN_PLANE_ONLY"


class PlateBehavior(Enum):
    Shell = "Shell"
    Membrane = "Membrane"


class PlateElementShape(Enum):
    Auto = "Auto"
    Triangle = "Triangle"
    Quad = "Quad"


class PlateMeshSettings(BaseModel):
    element_shape: PlateElementShape | None = None
    target_size: float | None = Field(
        None,
        description="Target element edge length. `None` meshes the boundary as-is (no interior\nrefinement).",
    )


class PlateOpening(BaseModel):
    boundary_node_ids: list[conint(ge=0)] | None = None
    id: conint(ge=0)


class PlatePressure(BaseModel):
    direction: list[float] = Field(..., max_length=3)
    id: conint(ge=0)
    load_case: conint(ge=0)
    magnitude: float
    plate_element_id: conint(ge=0) | None = Field(
        None, description="Target a single generated plate element."
    )
    projected: bool | None = Field(
        None,
        description="When true the pressure acts on the area projected onto `direction`\n(e.g. snow), otherwise on the true element area.",
    )
    surface_id: conint(ge=0) | None = Field(
        None, description="Target a whole surface (all its generated elements)."
    )


class PlateResultants(BaseModel):
    mx: float
    mxy: float
    my: float
    nx: float
    nxy: float
    ny: float
    qx: float
    qy: float


class PlateStiffnessModifiers(BaseModel):
    bending: float | None = None
    membrane: float | None = None
    shear: float | None = None


class PlateSurface(BaseModel):
    behavior: PlateBehavior | None = None
    boundary_node_ids: list[conint(ge=0)] = Field(
        ...,
        description="Outer boundary, referencing existing model nodes (counter-clockwise).",
    )
    classification: str | None = None
    generated_plate_element_ids: list[conint(ge=0)] | None = Field(
        None,
        description="Ids of the plate elements generated from this surface (populated by the\nmesher; input value is ignored).",
    )
    id: conint(ge=0)
    local_x_direction: list[float] | None = Field(None, max_length=3)
    material: conint(ge=0)
    mesh: PlateMeshSettings | None = None
    name: str | None = None
    offset: float | None = Field(
        None,
        description="Distance from the reference surface along the local plate normal.",
    )
    openings: list[PlateOpening] | None = Field(
        None,
        description="Holes in the surface; the mesher generates elements around them.",
    )
    stiffness_modifiers: PlateStiffnessModifiers | None = None
    thickness: float


class PressureUnit(Enum):
    Pa = "Pa"
    kPa = "kPa"
    MPa = "MPa"
    GPa = "GPa"


class ReactionNodeResult(BaseModel):
    location: NodeLocation
    nodal_forces: NodeForces
    support_id: conint(ge=0)


class ResultType1(BaseModel):
    Loadcase: conint(ge=0)


class ResultType2(BaseModel):
    Loadcombination: conint(ge=0)


class ResultType(RootModel[ResultType1 | ResultType2]):
    root: ResultType1 | ResultType2


class ResultsSummary(BaseModel):
    total_displacements: conint(ge=0)
    total_member_forces: conint(ge=0)
    total_plate_forces: conint(ge=0) | None = None
    total_reaction_forces: conint(ge=0)


class RigidStrategy(Enum):
    LinearMpc = "LinearMpc"
    RigidMember = "RigidMember"


class RotationImperfection(BaseModel):
    axis: list[float] = Field(..., max_length=3)
    magnitude: float
    memberset_ids: list[conint(ge=0)]


class Section(BaseModel):
    a_sy: float | None = Field(
        None,
        description="Effective shear area in Y-direction (m²). None = no shear deformation (Euler-Bernoulli).",
    )
    a_sz: float | None = Field(
        None,
        description="Effective shear area in Z-direction (m²). None = no shear deformation (Euler-Bernoulli).",
    )
    area: float
    b: float | None = None
    centroid_y: float | None = Field(
        None,
        description="Centroid Y-coordinate within the shape path coordinate system (mm).\nUsed by the viewer to offset shape-path extrusions so the centroid\naligns with the member node.  Not used by the solver.",
    )
    centroid_z: float | None = Field(
        None,
        description="Centroid Z-coordinate within the shape path coordinate system (mm).",
    )
    h: float | None = None
    i_w: float | None = Field(
        None,
        description="Warping constant (m⁶). None = no warping (pure St. Venant torsion).",
    )
    i_y: float
    i_yz: float | None = Field(
        None,
        description="Product of inertia about centroidal axes (mm⁴ in JSON, scaled to m⁴ by solver).\nNon-zero for asymmetric sections (e.g. angle, C-channel with unequal flanges).\nWhen present and non-zero, the solver auto-detects whether `i_y`/`i_z`\nare centroidal or principal values (by checking angle consistency) and\napplies or skips the principal-axis rotation accordingly.",
    )
    i_z: float
    id: conint(ge=0)
    j: float
    material: conint(ge=0)
    name: str
    principal_axis_angle: float | None = Field(
        None,
        description="Angle (degrees) from centroidal to principal axes.\nWhen `i_yz` is absent or zero, this angle is used to rotate the\nstiffness matrix from principal to centroidal frame.  When `i_yz`\nis present, the solver checks whether `i_y`/`i_z` are centroidal\n(angle matches formula) or principal (rotation applied).\nPositive = counter-clockwise.  Default 0.",
    )
    shape_path: conint(ge=0) | None = None
    wagner_coeff: float | None = Field(None, description="Wagner coefficient for lateral-torsional buckling.")
    y_s: float | None = Field(None, description="Shear center Y-coordinate relative to centroid (m).")
    z_s: float | None = Field(None, description="Shear center Z-coordinate relative to centroid (m).")


class SectionForce(BaseModel):
    forces: NodeForces
    x_frac: float


class ShapeCommand(BaseModel):
    center_y: float | None = None
    center_z: float | None = None
    command: str
    r: float | None = None
    theta0: float | None = None
    theta1: float | None = None
    y: float | None = None
    z: float | None = None


class ShapePath(BaseModel):
    id: conint(ge=0)
    name: str
    shape_commands: list[ShapeCommand]


class StiffnessCurveConfig(BaseModel):
    depends_on: ForceComponent = Field(..., description="Which force component the stiffness depends on.")
    points: list[list[float]] = Field(
        ...,
        description="Sorted `[force_value, stiffness]` pairs (≥ 2 points, positive stiffness).",
    )


class SupportConditionType(Enum):
    Fixed = "Fixed"
    Free = "Free"
    Spring = "Spring"
    PositiveOnly = "PositiveOnly"
    NegativeOnly = "NegativeOnly"


class SurfaceLoadVertex(BaseModel):
    x: float
    y: float
    z: float


class TranslationImperfection(BaseModel):
    axis: list[float] = Field(..., max_length=3)
    magnitude: float
    memberset_ids: list[conint(ge=0)]


class UnitSettings(BaseModel):
    densityUnit: DensityUnit | None = None
    forceUnit: ForceUnit | None = None
    lengthUnit: LengthUnit | None = None
    pressureUnit: PressureUnit | None = None
    system: str | None = None


class UnityCheck(BaseModel):
    check_id: str
    details: Any
    governing: GoverningKey | None = None
    limit: float | None = None
    message: str | None = None
    ok: bool
    value: float | None = None


class UnityCheckOverview(BaseModel):
    aggregated_ok: bool
    aggregated_value: float | None = None
    check_id: str
    children: list[UnityCheck]
    governing: GoverningKey | None = None


class WorkAxis(BaseModel):
    direction_x: float
    direction_y: float
    direction_z: float
    id: conint(ge=0)
    name: str | None = None
    origin_x: float
    origin_y: float
    origin_z: float


class WorkPlane(BaseModel):
    id: conint(ge=0)
    name: str | None = None
    normal_x: float
    normal_y: float
    normal_z: float
    origin_x: float
    origin_y: float
    origin_z: float


class AnalysisOptions(BaseModel):
    axial_slack: float | None = None
    dimensionality: Dimensionality
    enable_self_weight: bool | None = Field(
        None,
        description="When true, the engine generates self-weight (dead load) for every member\nfrom its material density and cross-sectional area, collected into a\nself-weight load case (see `self_weight_load_case_id`).  Cable members\ncarry their weight intrinsically in the catenary formulation and are\ntherefore excluded from the generated self-weight load.",
    )
    gravity_direction: list[float] | None = Field(
        None,
        description="Global gravity direction as a vector (normalized to a unit vector at use).\nDefault `(0, -1, 0)` — gravity acting in the negative Y direction.",
        max_length=3,
    )
    gravity_factor: float | None = Field(
        None,
        description="Signed gravitational acceleration magnitude in length-units/s².\nDefault `-9.81` (m/s²).  Self-weight per unit length is\n`w = density · area · |gravity_factor|` applied along `gravity_direction`.",
    )
    id: conint(ge=0)
    include_shear_center_coupling: bool | None = Field(
        None,
        description="When false, suppresses shear-center eccentricity coupling (T^T·K·T\ntransformation) by clearing y_s/z_s for all sections.  Some commercial\nsolvers do not apply this coupling; disabling it improves agreement.",
    )
    include_shear_deformation: bool | None = Field(
        None,
        description="When false, forces shear deformation factor φ=0 (Euler-Bernoulli) for all elements.",
    )
    include_warping: bool | None = Field(
        None,
        description="When false, ignores warping constant Iw and uses pure GJ/L torsion for all elements.",
    )
    max_iterations: conint(ge=0) | None = None
    nonlinear_method: NonlinearMethod | None = Field(
        None,
        description="Controls the nonlinear solver formulation (P_DELTA or COROTATIONAL).\nOnly affects second-order (nonlinear) analysis.",
    )
    order: AnalysisOrder
    pdelta_formulation: PdeltaFormulation | None = Field(
        None,
        description="Controls the geometric stiffness matrix formulation for P-Delta analysis.\n`Consistent` (default) uses full Przemieniecki K_g; `Simplified` uses\nP/L-only diagonal terms matching commercial solvers.",
    )
    pdelta_mode: PdeltaMode | None = Field(
        None,
        description="High-level P-Delta strategy.  `Full` (default) amplifies all directions.\n`InPlaneOnly` auto-detects the out-of-plane axis from the model's\nbounding box and suppresses it, matching commercial solver behavior.\nOverrides `pdelta_suppress_axes` when set to `InPlaneOnly`.",
    )
    pdelta_suppress_axes: list[str] | None = Field(
        None,
        description='Global translational axes to exclude from P-Delta amplification.\n\nWhen a structure is near buckling in an out-of-plane direction,\nthe consistent P-Delta amplification can produce forces that differ\nsignificantly from commercial solvers which\ntypically only amplify in-plane sway.\n\nSet to `["Z"]` for in-plane racks/portal frames where Z is out-of-plane,\nor `["X","Z"]` to limit P-Delta to Y-sway only.  Empty (default) means\nall translational directions are amplified.\n\nMaps to global DOFs: "X"→0,7  "Y"→1,8  "Z"→2,9  per element.',
    )
    rigid_strategy: RigidStrategy
    self_weight_load_case_id: conint(ge=0) | None = Field(
        None,
        description='Target load case id that generated self-weight loads are injected into.\nWhen set, the loads are added to that (typically empty "G") load case so\ncombinations can factor it (e.g. 1.35·G).  When `None` and self-weight is\nenabled, a new load case is created automatically.',
    )
    solve_loadcases: bool
    solver: str
    tolerance: float


class ImperfectionCase(BaseModel):
    imperfection_case_id: conint(ge=0)
    load_combinations: list[conint(ge=0)]
    rotation_imperfections: list[RotationImperfection]
    translation_imperfections: list[TranslationImperfection]


class Member(BaseModel):
    chi: float | None = None
    classification: str
    end_hinge: conint(ge=0) | None = None
    end_node_id: conint(ge=0)
    end_offset: MemberEndOffset | None = None
    id: conint(ge=0)
    member_type: MemberType
    mirror: bool | None = Field(
        None,
        description="When true, the cross-section is mirrored: shear-center offsets y_s and\nz_s are negated, and the shape_path geometry is flipped.",
    )
    pretension: float | None = Field(
        None,
        description="Initial cable tension (force units) for `Cable` members. Used to derive\nthe unstretched length when `unstretched_length` is not given directly:\n`L₀ = L_chord / (1 + pretension/EA)`.  Ignored for non-cable members.",
    )
    reference_member: conint(ge=0) | None = None
    reference_node: conint(ge=0) | None = None
    rotation_angle: float
    section: conint(ge=0) | None = None
    start_hinge: conint(ge=0) | None = None
    start_node_id: conint(ge=0)
    start_offset: MemberEndOffset | None = None
    unstretched_length: float | None = Field(
        None,
        description="Explicit unstretched (natural) length L₀ (length units) for `Cable`\nmembers.  Takes precedence over `pretension`.  When neither is set, the\ncable's unstretched length defaults to the straight chord length.",
    )
    weight: float


class MemberHinge(BaseModel):
    hinge_type: str
    id: conint(ge=0)
    max_bimoment_warp: float | None = None
    max_moment_mx: float | None = None
    max_moment_my: float | None = None
    max_moment_mz: float | None = None
    max_tension_vx: float | None = None
    max_tension_vy: float | None = None
    max_tension_vz: float | None = None
    rotational_release_mx: float | None = None
    rotational_release_my: float | None = None
    rotational_release_mz: float | None = None
    rotational_release_warp: float | None = None
    stiffness_curve_mx: StiffnessCurveConfig | None = None
    stiffness_curve_my: StiffnessCurveConfig | None = None
    stiffness_curve_mz: StiffnessCurveConfig | None = None
    stiffness_curve_vx: StiffnessCurveConfig | None = None
    stiffness_curve_vy: StiffnessCurveConfig | None = None
    stiffness_curve_vz: StiffnessCurveConfig | None = None
    translational_release_vx: float | None = None
    translational_release_vy: float | None = None
    translational_release_vz: float | None = None


class MemberResult(BaseModel):
    end_node_forces: NodeForces
    local_displacement_end_node: NodeDisplacement
    local_displacement_start_node: NodeDisplacement
    local_end_forces: NodeForces
    local_maximums: NodeForces
    local_minimums: NodeForces
    local_start_forces: NodeForces
    maximums: NodeForces
    minimums: NodeForces
    section_forces: list[SectionForce]
    start_node_forces: NodeForces


class MemberSet(BaseModel):
    classification: str | None = None
    id: conint(ge=0)
    l_y: float | None = None
    l_z: float | None = None
    members: list[Member]


class PlateElement(BaseModel):
    behavior: PlateBehavior | None = None
    id: conint(ge=0)
    local_x_direction: list[float] | None = Field(None, max_length=3)
    material: conint(ge=0)
    node_ids: list[conint(ge=0)]
    offset: float | None = Field(
        None,
        description="Distance from the reference surface along the local plate normal.",
    )
    source_surface_id: conint(ge=0) | None = Field(
        None, description="The `PlateSurface` this element was meshed from, if any."
    )
    stiffness_modifiers: PlateStiffnessModifiers | None = None
    thickness: float


class PlateResult(BaseModel):
    centroid: NodeLocation
    centroid_displacement_global: NodeDisplacement
    centroid_displacement_local: NodeDisplacement
    nodal_forces_global: dict[str, NodeForces]
    plate_id: conint(ge=0)
    resultants: PlateResultants


class Results(BaseModel):
    displacement_nodes: dict[str, NodeDisplacement]
    member_results: dict[str, MemberResult]
    name: str
    plate_results: dict[str, PlateResult] | None = None
    reaction_nodes: dict[str, ReactionNodeResult]
    result_type: ResultType
    summary: ResultsSummary
    unity_checks: dict[str, UnityCheck] | None = None


class ResultsBundle(BaseModel):
    loadcases: dict[str, Results]
    loadcombinations: dict[str, Results]
    unity_checks_overview: dict[str, UnityCheckOverview] | None = None


class Settings(BaseModel):
    analysis_options: AnalysisOptions
    general_info: GeneralInfo
    id: conint(ge=0)
    unit_settings: UnitSettings


class SupportCondition(BaseModel):
    condition_type: SupportConditionType
    stiffness: float | None = None
    stiffness_curve: StiffnessCurveConfig | None = None


class SurfaceLoad(BaseModel):
    direction: list[float] = Field(..., max_length=3)
    distribution_direction: list[float] | None = Field(None, max_length=3)
    id: conint(ge=0)
    load_case: conint(ge=0)
    magnitude: float
    polygon: list[SurfaceLoadVertex]


class LoadCase(BaseModel):
    distributed_loads: list[DistributedLoad]
    id: conint(ge=0)
    member_point_loads: list[MemberPointLoad] | None = None
    member_point_moments: list[MemberPointMoment] | None = None
    name: str
    nodal_loads: list[NodalLoad]
    nodal_moments: list[NodalMoment]
    plate_pressures: list[PlatePressure] | None = None
    rotation_imperfections: list[RotationImperfection]
    surface_loads: list[SurfaceLoad] | None = None
    translation_imperfections: list[TranslationImperfection]


class NodalSupport(BaseModel):
    classification: str | None = None
    displacement_conditions: dict[str, SupportCondition]
    id: conint(ge=0)
    rotation_conditions: dict[str, SupportCondition]
    warping_condition: SupportCondition | None = None


class FERS(BaseModel):
    entity_groups: list[EntityGroup] | None = Field(
        None,
        description="Generic, calculation-agnostic entity groups for UI/visualization.",
    )
    imperfection_cases: list[ImperfectionCase]
    load_cases: list[LoadCase]
    load_combinations: list[LoadCombination]
    materials: list[Material]
    member_sets: list[MemberSet]
    memberhinges: list[MemberHinge] | None = None
    nodal_supports: list[NodalSupport]
    nodes: list[Node] | None = None
    plate_elements: list[PlateElement] | None = None
    plate_surfaces: list[PlateSurface] | None = None
    results: ResultsBundle | None = None
    sections: list[Section]
    settings: Settings
    shape_paths: list[ShapePath] | None = None
    work_axes: list[WorkAxis] | None = None
    work_planes: list[WorkPlane] | None = None
