# generated by datamodel-codegen:
#   filename:  openapi.json
#   timestamp: 2026-04-20T14:08:43+00:00

from __future__ import annotations

from enum import Enum
from typing import Any

from pydantic import BaseModel, Field, RootModel, conint


class AnalysisOrder(Enum):
    LINEAR = "LINEAR"
    NONLINEAR = "NONLINEAR"


class DensityUnit(Enum):
    kg_m3 = "kg/m3"
    kg_mm3 = "kg/mm3"


class Dimensionality(Enum):
    field_2D = "2D"
    field_3D = "3D"


class DistributedLoad(BaseModel):
    direction: list[Any]
    end_frac: float
    end_magnitude: float
    load_case: conint(ge=0)
    magnitude: float
    member: conint(ge=0)
    start_frac: float


class ForceComponent(Enum):
    N = "N"
    Vy = "Vy"
    Vz = "Vz"
    Mx = "Mx"
    My = "My"
    Mz = "Mz"
    Fx = "Fx"
    Fy = "Fy"
    Fz = "Fz"


class ForceUnit(Enum):
    N = "N"
    kN = "kN"


class GeneralInfo(BaseModel):
    author: str
    project_name: str
    version: str


class GoverningKey(BaseModel):
    load_case_id: conint(ge=0) | None = None
    load_combination_id: conint(ge=0) | None = None
    member_id: conint(ge=0) | None = None


class LengthUnit(Enum):
    mm = "mm"
    cm = "cm"
    m = "m"


class LimitState(Enum):
    SLS = "SLS"
    ULS = "ULS"
    FLS = "FLS"
    ALS = "ALS"


class LoadCombination(BaseModel):
    check: str
    id: conint(ge=0)
    limit_state: LimitState | None = None
    load_cases_factors: dict[str, float]
    name: str
    situation: str | None = None


class Material(BaseModel):
    density: float
    e_mod: float
    g_mod: float
    id: conint(ge=0)
    name: str
    yield_stress: float


class MemberType(Enum):
    Normal = "Normal"
    Truss = "Truss"
    Tension = "Tension"
    Compression = "Compression"
    Rigid = "Rigid"


class NodalLoad(BaseModel):
    direction: list[Any]
    id: conint(ge=0)
    load_case: conint(ge=0)
    load_type: str
    magnitude: float
    node: conint(ge=0)


class NodalMoment(BaseModel):
    direction: list[Any]
    id: conint(ge=0)
    load_case: conint(ge=0)
    load_type: str
    magnitude: float
    node: conint(ge=0)


class Node(BaseModel):
    X: float
    Y: float
    Z: float
    id: conint(ge=0)
    nodal_support: conint(ge=0) | None = None


class NodeDisplacement(BaseModel):
    dx: float
    dy: float
    dz: float
    rx: float
    ry: float
    rz: float
    warp: float | None = None


class NodeForces(BaseModel):
    bw: float | None = None
    fx: float
    fy: float
    fz: float
    mx: float
    my: float
    mz: float


class NodeLocation(BaseModel):
    X: float
    Y: float
    Z: float


class NonlinearMethod(Enum):
    P_DELTA = "P_DELTA"
    COROTATIONAL = "COROTATIONAL"


class PdeltaFormulation(Enum):
    CONSISTENT = "CONSISTENT"
    SIMPLIFIED = "SIMPLIFIED"


class PdeltaMode(Enum):
    FULL = "FULL"
    IN_PLANE_ONLY = "IN_PLANE_ONLY"


class PressureUnit(Enum):
    Pa = "Pa"
    kPa = "kPa"
    MPa = "MPa"
    GPa = "GPa"


class ReactionNodeResult(BaseModel):
    location: NodeLocation
    nodal_forces: NodeForces
    support_id: conint(ge=0)


class ResultType1(BaseModel):
    Loadcase: conint(ge=0)


class ResultType2(BaseModel):
    Loadcombination: conint(ge=0)


class ResultType(RootModel[ResultType1 | ResultType2]):
    root: ResultType1 | ResultType2


class ResultsSummary(BaseModel):
    total_displacements: conint(ge=0)
    total_member_forces: conint(ge=0)
    total_reaction_forces: conint(ge=0)


class RigidStrategy(Enum):
    LinearMpc = "LinearMpc"
    RigidMember = "RigidMember"


class RotationImperfection(BaseModel):
    axis: list[Any]
    magnitude: float
    memberset_ids: list[conint(ge=0)]


class Section(BaseModel):
    a_sy: float | None = Field(
        None,
        description=(
            "Effective shear area in Y-direction (m²). " "None = no shear deformation (Euler-Bernoulli)."
        ),
    )
    a_sz: float | None = Field(
        None,
        description=(
            "Effective shear area in Z-direction (m²). " "None = no shear deformation (Euler-Bernoulli)."
        ),
    )
    area: float
    b: float | None = None
    centroid_y: float | None = Field(
        None,
        description=(
            "Centroid Y-coordinate within the shape path coordinate system (mm).\n"
            "Used by the viewer to offset shape-path extrusions so the centroid\n"
            "aligns with the member node.  Not used by the solver."
        ),
    )
    centroid_z: float | None = Field(
        None,
        description="Centroid Z-coordinate within the shape path coordinate system (mm).",
    )
    h: float | None = None
    i_w: float | None = Field(
        None,
        description="Warping constant (m⁶). None = no warping (pure St. Venant torsion).",
    )
    i_y: float
    i_yz: float | None = Field(
        None,
        description=(
            "Product of inertia about centroidal axes "
            "(mm⁴ in JSON, scaled to m⁴ by solver).\n"
            "Non-zero for asymmetric sections "
            "(e.g. angle, C-channel with unequal flanges).\n"
            "When present and non-zero, the solver auto-detects whether "
            "`i_y`/`i_z` are centroidal or principal values "
            "(by checking angle consistency) and "
            "applies or skips the principal-axis rotation accordingly."
        ),
    )
    i_z: float
    id: conint(ge=0)
    j: float
    material: conint(ge=0)
    name: str
    principal_axis_angle: float | None = Field(
        None,
        description=(
            "Angle (degrees) from centroidal to principal axes.\n"
            "When `i_yz` is absent or zero, this angle is used to "
            "rotate the stiffness matrix from principal to "
            "centroidal frame.  When `i_yz` is present, the solver "
            "checks whether `i_y`/`i_z` are centroidal "
            "(angle matches formula) or principal "
            "(rotation applied).\n"
            "Positive = counter-clockwise.  Default 0."
        ),
    )
    shape_path: conint(ge=0) | None = None
    wagner_coeff: float | None = Field(None, description="Wagner coefficient for lateral-torsional buckling.")
    y_s: float | None = Field(None, description="Shear center Y-coordinate relative to centroid (m).")
    z_s: float | None = Field(None, description="Shear center Z-coordinate relative to centroid (m).")


class SectionForce(BaseModel):
    forces: NodeForces
    x_frac: float


class ShapeCommand(BaseModel):
    center_y: float | None = None
    center_z: float | None = None
    command: str
    r: float | None = None
    theta0: float | None = None
    theta1: float | None = None
    y: float | None = None
    z: float | None = None


class ShapePath(BaseModel):
    id: conint(ge=0)
    name: str
    shape_commands: list[ShapeCommand]


class StiffnessCurveConfig(BaseModel):
    depends_on: ForceComponent = Field(..., description="Which force component the stiffness depends on.")
    points: list[list[float]] = Field(
        ...,
        description="Sorted `[force_value, stiffness]` pairs (≥ 2 points, positive stiffness).",
    )


class SupportConditionType(Enum):
    Fixed = "Fixed"
    Free = "Free"
    Spring = "Spring"
    PositiveOnly = "PositiveOnly"
    NegativeOnly = "NegativeOnly"


class TranslationImperfection(BaseModel):
    axis: list[Any]
    magnitude: float
    memberset_ids: list[conint(ge=0)]


class UnitSettings(BaseModel):
    densityUnit: DensityUnit | None = None
    forceUnit: ForceUnit | None = None
    lengthUnit: LengthUnit | None = None
    pressureUnit: PressureUnit | None = None
    system: str | None = None


class UnityCheck(BaseModel):
    check_id: str
    details: Any
    governing: GoverningKey | None = None
    limit: float | None = None
    message: str | None = None
    ok: bool
    value: float | None = None


class UnityCheckOverview(BaseModel):
    aggregated_ok: bool
    aggregated_value: float | None = None
    check_id: str
    children: list[UnityCheck]
    governing: GoverningKey | None = None


class AnalysisOptions(BaseModel):
    axial_slack: float | None = None
    dimensionality: Dimensionality
    id: conint(ge=0)
    include_shear_center_coupling: bool | None = Field(
        None,
        description=(
            "When false, suppresses shear-center eccentricity "
            "coupling (T^T·K·T transformation) by clearing "
            "y_s/z_s for all sections.  Some commercial solvers "
            "do not apply this coupling; disabling it improves "
            "agreement."
        ),
    )
    include_shear_deformation: bool | None = Field(
        None,
        description="When false, forces shear deformation factor φ=0 (Euler-Bernoulli) for all elements.",
    )
    include_warping: bool | None = Field(
        None,
        description="When false, ignores warping constant Iw and uses pure GJ/L torsion for all elements.",
    )
    max_iterations: conint(ge=0) | None = None
    nonlinear_method: NonlinearMethod | None = Field(
        None,
        description=(
            "Controls the nonlinear solver formulation "
            "(P_DELTA or COROTATIONAL).\n"
            "Only affects second-order (nonlinear) analysis."
        ),
    )
    order: AnalysisOrder
    pdelta_formulation: PdeltaFormulation | None = Field(
        None,
        description=(
            "Controls the geometric stiffness matrix formulation "
            "for P-Delta analysis.\n"
            "`Consistent` (default) uses full Przemieniecki K_g; "
            "`Simplified` uses P/L-only diagonal terms matching "
            "commercial solvers."
        ),
    )
    pdelta_mode: PdeltaMode | None = Field(
        None,
        description=(
            "High-level P-Delta strategy.  `Full` (default) "
            "amplifies all directions.\n"
            "`InPlaneOnly` auto-detects the out-of-plane axis "
            "from the model's bounding box and suppresses it, "
            "matching commercial solver behavior.\n"
            "Overrides `pdelta_suppress_axes` when set to "
            "`InPlaneOnly`."
        ),
    )
    pdelta_suppress_axes: list[str] | None = Field(
        None,
        description=(
            "Global translational axes to exclude from "
            "P-Delta amplification.\n\n"
            "When a structure is near buckling in an "
            "out-of-plane direction, the consistent P-Delta "
            "amplification can produce forces that differ "
            "significantly from commercial solvers which "
            "typically only amplify in-plane sway.\n\n"
            'Set to `["Z"]` for in-plane racks/portal frames '
            'where Z is out-of-plane, or `["X","Z"]` to limit '
            "P-Delta to Y-sway only.  Empty (default) means "
            "all translational directions are amplified.\n\n"
            'Maps to global DOFs: "X"→0,7  "Y"→1,8  '
            '"Z"→2,9  per element.'
        ),
    )
    rigid_strategy: RigidStrategy
    solve_loadcases: bool
    solver: str
    tolerance: float


class ImperfectionCase(BaseModel):
    imperfection_case_id: conint(ge=0)
    load_combinations: list[conint(ge=0)]
    rotation_imperfections: list[RotationImperfection]
    translation_imperfections: list[TranslationImperfection]


class LoadCase(BaseModel):
    distributed_loads: list[DistributedLoad]
    id: conint(ge=0)
    name: str
    nodal_loads: list[NodalLoad]
    nodal_moments: list[NodalMoment]
    rotation_imperfections: list[RotationImperfection]
    translation_imperfections: list[TranslationImperfection]


class Member(BaseModel):
    chi: float | None = None
    classification: str
    end_hinge: conint(ge=0) | None = None
    end_node: Node
    id: conint(ge=0)
    member_type: MemberType
    mirror: bool | None = Field(
        None,
        description=(
            "When true, the cross-section is mirrored: "
            "shear-center offsets y_s and z_s are negated, "
            "and the shape_path geometry is flipped."
        ),
    )
    reference_member: conint(ge=0) | None = None
    reference_node: conint(ge=0) | None = None
    rotation_angle: float
    section: conint(ge=0) | None = None
    start_hinge: conint(ge=0) | None = None
    start_node: Node
    weight: float


class MemberHinge(BaseModel):
    hinge_type: str
    id: conint(ge=0)
    max_bimoment_warp: float | None = None
    max_moment_mx: float | None = None
    max_moment_my: float | None = None
    max_moment_mz: float | None = None
    max_tension_vx: float | None = None
    max_tension_vy: float | None = None
    max_tension_vz: float | None = None
    rotational_release_mx: float | None = None
    rotational_release_my: float | None = None
    rotational_release_mz: float | None = None
    rotational_release_warp: float | None = None
    stiffness_curve_mx: StiffnessCurveConfig | None = None
    stiffness_curve_my: StiffnessCurveConfig | None = None
    stiffness_curve_mz: StiffnessCurveConfig | None = None
    stiffness_curve_vx: StiffnessCurveConfig | None = None
    stiffness_curve_vy: StiffnessCurveConfig | None = None
    stiffness_curve_vz: StiffnessCurveConfig | None = None
    translational_release_vx: float | None = None
    translational_release_vy: float | None = None
    translational_release_vz: float | None = None


class MemberResult(BaseModel):
    end_node_forces: NodeForces
    local_displacement_end_node: NodeDisplacement
    local_displacement_start_node: NodeDisplacement
    local_end_forces: NodeForces
    local_maximums: NodeForces
    local_minimums: NodeForces
    local_start_forces: NodeForces
    maximums: NodeForces
    minimums: NodeForces
    section_forces: list[SectionForce]
    start_node_forces: NodeForces


class MemberSet(BaseModel):
    classification: str | None = None
    id: conint(ge=0)
    l_y: float | None = None
    l_z: float | None = None
    members: list[Member]


class Results(BaseModel):
    displacement_nodes: dict[str, NodeDisplacement]
    member_results: dict[str, MemberResult]
    name: str
    reaction_nodes: dict[str, ReactionNodeResult]
    result_type: ResultType
    summary: ResultsSummary
    unity_checks: dict[str, UnityCheck] | None = None


class ResultsBundle(BaseModel):
    loadcases: dict[str, Results]
    loadcombinations: dict[str, Results]
    unity_checks_overview: dict[str, UnityCheckOverview] | None = None


class Settings(BaseModel):
    analysis_options: AnalysisOptions
    general_info: GeneralInfo
    id: conint(ge=0)
    unit_settings: UnitSettings


class SupportCondition(BaseModel):
    condition_type: SupportConditionType
    stiffness: float | None = None
    stiffness_curve: StiffnessCurveConfig | None = None


class NodalSupport(BaseModel):
    classification: str | None = None
    displacement_conditions: dict[str, SupportCondition]
    id: conint(ge=0)
    rotation_conditions: dict[str, SupportCondition]
    warping_condition: SupportCondition | None = None


class FERS(BaseModel):
    imperfection_cases: list[ImperfectionCase]
    load_cases: list[LoadCase]
    load_combinations: list[LoadCombination]
    materials: list[Material]
    member_sets: list[MemberSet]
    memberhinges: list[MemberHinge] | None = None
    nodal_supports: list[NodalSupport]
    results: ResultsBundle | None = None
    sections: list[Section]
    settings: Settings
    shape_paths: list[ShapePath] | None = None
