"""Regenerate ``fers_core/sections/_aisc_data.py`` from the AISC Shapes Database v16.0.

AISC fills what British Steel does not roll: W and HP sizes missing from British
Steel's ASTM datasheet, rectangular and round HSS, and pipe. Where both list a
shape, British Steel's row wins and AISC's is left out, so a name never carries
two sets of values.

The workbook is pinned by URL and SHA-256 and never committed. Rows keep the
Manual's US customary values as tabulated; ``fers_core/sections/aisc.py`` converts
them to SI.

Usage::

    python scripts/import_aisc.py [--xlsx PATH]

Needs ``openpyxl`` (requirements-dev.txt).
"""

from __future__ import annotations

import argparse
import hashlib
import os
import subprocess
import sys
import tempfile
import urllib.request

import openpyxl

_ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
_OUT = os.path.join(_ROOT, "fers_core", "sections", "_aisc_data.py")

_URL = "https://cloud.aisc.org/biggie_bin/aisc-shapes-database-v160-2.xlsx"
_SHA256 = "82d0ceb96a0d938ae1a6bd9637cb10a1e269225b5d668dce5b0bdc8d86013496"

# The sheet's US block comes first and a metric block with the same headers
# after it; columns are read from the first occurrence only.
_COLS = {
    "I": ("W", "A", "d", "bf", "tw", "tf", "kdes", "Ix", "Iy", "Sx", "Sy", "Zx", "Zy", "J", "Cw", "metric"),
    "RECT": ("W", "A", "Ht", "B", "tdes", "Ix", "Iy", "Sx", "Sy", "Zx", "Zy", "J", "metric"),
    "ROUND": ("W", "A", "OD", "tdes", "Ix", "Sx", "Zx", "J", "metric"),
}  # fmt: skip

# FERS family -> (AISC Type, column set, expected rows after British Steel's are dropped)
_FAMILIES = {
    "W": ("W", "I", 129),
    "HP": ("HP", "I", 11),
    "HSS": ("HSS", "RECT", 525),
    "HSSR": ("HSS", "ROUND", 189),
    "PIPE": ("PIPE", "ROUND", 51),
}


def _fetch(xlsx: str | None, tmp: str) -> str:
    path = xlsx or os.path.join(tmp, "aisc.xlsx")
    if xlsx is None:
        urllib.request.urlretrieve(_URL, path)
    with open(path, "rb") as f:
        got = hashlib.sha256(f.read()).hexdigest()
    if got != _SHA256:
        raise SystemExit(
            f"AISC workbook SHA-256 is {got}, pinned {_SHA256}.\n"
            "AISC re-issued the database: review the changes, then update _SHA256."
        )
    return path


def _british_steel_names() -> set[str]:
    sys.path.insert(0, _ROOT)
    from fers_core.sections import british_steel

    return {name for rows, _, _ in british_steel.FAMILIES.values() for name in rows}


def _number(v) -> str:
    if isinstance(v, (int, float)) and not isinstance(v, bool):
        return repr(float(v))
    raise ValueError(f"not a number: {v!r}")


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    ap.add_argument("--xlsx", help="read the workbook from here instead of downloading it")
    args = ap.parse_args()

    taken = _british_steel_names()
    with tempfile.TemporaryDirectory() as tmp:
        wb = openpyxl.load_workbook(_fetch(args.xlsx, tmp), read_only=True, data_only=True)
        sheet = wb["Database v16.0"]
        rows = sheet.iter_rows(values_only=True)
        header = next(rows)
        col = {}
        for i, h in enumerate(header):
            col.setdefault(h, i)
        # The metric block's own EDI name ("W250X32.7"), not the US block's.
        metric_col = max(i for i, h in enumerate(header) if h == "EDI_Std_Nomenclature")
        records = list(rows)

    tables: dict[str, dict[str, tuple]] = {}
    for family, (aisc_type, kind, count) in _FAMILIES.items():
        out: dict[str, tuple] = {}
        for r in records:
            if r[col["Type"]] != aisc_type:
                continue
            round_ = isinstance(r[col["OD"]], (int, float))
            if aisc_type == "HSS" and round_ != (kind == "ROUND"):
                continue
            label = r[col["AISC_Manual_Label"]]
            if label in taken:
                continue
            values = []
            for c in _COLS[kind]:
                if c == "metric":
                    values.append(repr(r[metric_col]))
                elif c == "Cw" and not isinstance(r[col["Cw"]], (int, float)):
                    values.append("None")
                else:
                    values.append(_number(r[col[c]]))
            out[label] = tuple(values)
        if len(out) != count:
            raise SystemExit(f"{family}: {len(out)} rows, expected {count}")
        tables[family] = out

    lines = [
        "# ruff: noqa: E501",
        "# Section data: AISC Shapes Database v16.0. Attribution and terms: https://ferscloud.com/legal-notice/imprint",
        "# Generated by scripts/import_aisc.py from the pinned AISC workbook. Do not edit by hand.",
        '"""AISC shapes as tabulated in US customary units (in, in2, in3, in4, in6, lb/ft).',
        "",
        "Only shapes British Steel's datasheets do not list. Each row follows",
        '``COLS[<kind>]``; ``KIND`` maps a family to its kind."""',
        "",
        f"COLS = {_COLS!r}",
        f"KIND = {{{', '.join(f'{f!r}: {k!r}' for f, (_, k, _) in _FAMILIES.items())}}}",
        "",
        "# fmt: off",
    ]
    for family, table in tables.items():
        lines.append(f"{family}: dict[str, tuple] = {{")
        for name, row in table.items():
            lines.append(f"    {name!r}: ({', '.join(row)}),")
        lines.append("}")
        lines.append("")
    lines.append("# fmt: on")
    with open(_OUT, "w", encoding="utf-8", newline="\n") as f:
        f.write("\n".join(lines) + "\n")
    subprocess.run([sys.executable, "-m", "ruff", "format", _OUT], check=False)
    print(f"wrote {sum(len(t) for t in tables.values())} sections to {os.path.relpath(_OUT, _ROOT)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
